### ISSUE TITLE
Fix deprecation warning, _headers is deprecated in Node 12

### ISSUE THREAD

**Issue by mcollina** [fastify/light-my-request#44]
```
(node:34152) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
    at new Response (/Users/matteo/Repositories/fastify-static/node_modules/light-my-request/lib/response.js:16:17)
    at /Users/matteo/Repositories/fastify-static/node_modules/light-my-request/index.js:86:19
    at new Promise (<anonymous>)
    at inject (/Users/matteo/Repositories/fastify-static/node_modules/light-my-request/index.js:84:12)
    at /Users/matteo/Repositories/fastify-static/node_modules/fastify/fastify.js:292:21
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by Eomm** [comment]
This issue has been fixed

Closing

**Comment by soufianebounira11** [comment]
help pls. 
(node:2652) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is
deprecated

**Comment by mcollina** [comment]
Which version of light-my-request are you using?
